# Generated by Django 5.1.4 on 2025-03-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_comment_ip_comment_time_comment_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='vote_sum',
            field=models.IntegerField(default=0),
        ),
    ]
