# Generated by Django 5.1.4 on 2025-04-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_article_vote_count_article_vote_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='authors'),
        ),
    ]
